pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // IronSource LevelPlay SDK
        maven { url 'https://android-sdk.is.com/' }
    }
}

rootProject.name = "Word Journeys"
include ':app'
