"""
Generate definitions for 3-letter and 7-letter words in words.json.
Uses hardcoded verified definitions.
"""
import json
import os

DEFINITIONS_3 = {
    "ACE": "A playing card with a single pip; also an expert",
    "ACT": "To take action or perform a role; a deed",
    "ADD": "To join or combine numbers or things together",
    "AGE": "The length of time a person or thing has existed",
    "AGO": "Before the present; in the past",
    "AID": "Help or support given to someone in need",
    "AIM": "To point or direct at a target; a purpose",
    "AIR": "The invisible gaseous substance surrounding the earth",
    "ALL": "Every one of; the whole amount or extent",
    "AND": "Used to connect words or clauses together",
    "ANT": "A small insect living in organized colonies",
    "ANY": "One or some, no matter which or how much",
    "APE": "A large primate without a tail; to imitate",
    "ARC": "A curved line forming part of a circle",
    "ARE": "Second-person present tense of the verb 'to be'",
    "ARK": "A large boat, as in Noah's vessel in the Bible",
    "ARM": "The upper limb of the human body; a weapon",
    "ART": "Creative expression through visual or performing media",
    "ASK": "To put a question to someone; to request",
    "ATE": "Past tense of 'eat'; consumed food",
    "AWE": "A feeling of reverential respect mixed with wonder",
    "AXE": "A tool with a heavy blade used for chopping",
    "BAD": "Of poor quality; not good; unpleasant",
    "BAG": "A flexible container with an opening at the top",
    "BAN": "To officially prohibit or forbid something",
    "BAR": "A long rod or block; a place serving drinks",
    "BAT": "A flying mammal; a club used in sports",
    "BAY": "A broad inlet of the sea; to howl or bark",
    "BED": "A piece of furniture for sleeping on",
    "BET": "To risk money on the outcome of an event",
    "BIG": "Of considerable size, extent, or intensity",
    "BIT": "A small piece or amount of something",
    "BOW": "To bend the upper body forward; a knot with loops",
    "BOX": "A container with flat sides and a lid",
    "BOY": "A male child or young man",
    "BUD": "A growth on a plant that develops into a flower",
    "BUG": "A small insect; a fault in a computer program",
    "BUN": "A small round bread roll; a hairstyle",
    "BUS": "A large vehicle carrying passengers by road",
    "BUT": "Used to introduce a contrasting statement",
    "BUY": "To obtain something in exchange for payment",
    "CAB": "A taxi; the driver's compartment in a vehicle",
    "CAN": "To be able to; a cylindrical metal container",
    "CAP": "A soft hat with a visor; a lid or cover",
    "CAR": "A road vehicle powered by an engine",
    "CAT": "A small domesticated carnivorous mammal",
    "COP": "A police officer; to catch or seize",
    "COT": "A small portable bed, especially for a child",
    "COW": "A fully grown female animal of cattle",
    "CRY": "To shed tears; to call out loudly",
    "CUB": "The young of a fox, bear, lion, or similar animal",
    "CUP": "A small container for drinking from",
    "CUR": "An aggressive or unkempt dog; a despicable person",
    "CUT": "To make an opening or wound with a sharp edge",
    "DAB": "To press lightly; a small amount of something",
    "DAD": "One's father; an informal term for father",
    "DAM": "A barrier built across a river to hold back water",
    "DAY": "A period of twenty-four hours; the time of light",
    "DEN": "A wild animal's lair; a small private room",
    "DEW": "Tiny drops of water that form on surfaces at night",
    "DID": "Past tense of 'do'; performed an action",
    "DIG": "To break up and move earth; to excavate",
    "DIM": "Not bright or clear; lacking in light",
    "DIP": "To lower briefly into a liquid; a brief swim",
    "DOC": "A doctor; an informal term for physician",
    "DOG": "A domesticated carnivorous mammal kept as a pet",
    "DOT": "A small round mark or spot",
    "DRY": "Free from moisture or liquid; not wet",
    "DUB": "To give a name or nickname; to add sound to film",
    "DUE": "Expected at or planned for a certain time",
    "DUG": "Past tense of 'dig'; excavated earth",
    "DUN": "A dull grayish-brown color; to make persistent demands",
    "DUO": "A pair of people or things; two performers together",
    "DYE": "A substance used to color materials or hair",
    "EAR": "The organ of hearing in humans and animals",
    "EAT": "To put food into the mouth, chew, and swallow",
    "EEL": "A long snake-like fish that lives in water",
    "EGG": "An oval body laid by a female bird, containing an embryo",
    "ELF": "A supernatural being in folklore, typically small",
    "ELK": "A large deer with branching antlers",
    "ELM": "A tall deciduous tree with broad leaves",
    "EMU": "A large flightless bird native to Australia",
    "END": "The final part of something; to bring to a close",
    "ERA": "A long and distinct period of history",
    "EVE": "The day or period before a special event",
    "EWE": "A female sheep",
    "EYE": "The organ of sight in humans and animals",
    "FAN": "A device for creating a current of air; an enthusiast",
    "FAR": "At, to, or by a great distance; remote",
    "FAT": "A natural oily substance in animal bodies",
    "FAX": "An exact copy of a document sent electronically",
    "FED": "Past tense of 'feed'; gave food to someone",
    "FEW": "Not many; a small number of",
    "FIG": "A soft sweet fruit with many small seeds",
    "FIN": "A flat appendage on a fish used for swimming",
    "FIR": "An evergreen coniferous tree with needle-like leaves",
    "FIT": "Suitable or appropriate; in good physical condition",
    "FIX": "To repair or mend; to fasten securely",
    "FLY": "To move through the air using wings; a winged insect",
    "FOB": "A chain attached to a pocket watch; to deceive",
    "FOE": "An enemy or opponent in conflict or competition",
    "FOG": "A thick cloud of tiny water droplets near the ground",
    "FOR": "Indicating the purpose or recipient of an action",
    "FOX": "A wild carnivorous mammal with a bushy tail",
    "FRY": "To cook in hot fat or oil",
    "FUN": "Enjoyment or amusement; lighthearted pleasure",
    "FUR": "The short fine soft hair of certain animals",
    "GAG": "A piece of cloth put in the mouth to prevent speaking",
    "GAP": "A space or opening in something; an unfilled interval",
    "GAS": "An air-like fluid substance; fuel for vehicles",
    "GAY": "Lighthearted and carefree; relating to homosexuality",
    "GEL": "A semi-solid substance used in cosmetics",
    "GEM": "A precious or semiprecious stone; something valued",
    "GET": "To come to have or hold; to receive or obtain",
    "GIG": "A live performance of music; a job or engagement",
    "GIN": "A clear alcoholic spirit flavored with juniper berries",
    "GNU": "A large African antelope with a long head and beard",
    "GOD": "A superhuman being worshipped as having power over nature",
    "GOT": "Past tense of 'get'; came to have or possess",
    "GUM": "A sticky substance from trees; the flesh around teeth",
}

DEFINITIONS_7 = {
    "ABANDON": "To give up completely; to desert or leave behind",
    "ABILITY": "The possession of skill or talent to do something",
    "ABOLISH": "To formally put an end to a system or practice",
    "ABSENCE": "The state of being away from a place or person",
    "ABSOLVE": "To declare someone free from guilt or blame",
    "ABSTAIN": "To restrain oneself from doing something",
    "ACADEMY": "A place of study or training; a scholarly society",
    "ACCLAIM": "Enthusiastic and public praise or approval",
    "ACCOUNT": "A report or description of an event; a bank record",
    "ACHIEVE": "To successfully bring about or reach a desired result",
    "ACQUIRE": "To buy or obtain something for oneself",
    "ADAPTED": "Made suitable for a new use or purpose; adjusted",
    "ADDRESS": "The particulars of where a person lives or works",
    "ADOPTED": "Legally taken another's child as one's own",
    "ADVANCE": "To move forward or make progress; an improvement",
    "ADVERSE": "Preventing success or development; harmful",
    "ADVISED": "Recommended a course of action; gave counsel",
    "AGAINST": "In opposition to; disagreeing with",
    "AGILITY": "The ability to move quickly and easily",
    "AIRPORT": "A complex of buildings for aircraft operations",
    "ALREADY": "Before or by now; as early as this",
    "ALTERED": "Changed in character or composition; modified",
    "AMATEUR": "A person who does something for pleasure, not profession",
    "AMAZING": "Causing great surprise or wonder; astonishing",
    "AMNESTY": "An official pardon for people convicted of offenses",
    "AMPLIFY": "To increase the volume or strength of something",
    "ANALOGY": "A comparison between things for the purpose of explanation",
    "ANALYZE": "To examine something in detail to understand it",
    "ANCIENT": "Belonging to the very distant past; very old",
    "ANGULAR": "Having angles or sharp corners; lean and bony",
    "ANIMALS": "Living organisms that feed on organic matter",
    "ANOTHER": "Used to refer to an additional person or thing",
    "ANTIQUE": "An object valuable because of its age; old-fashioned",
    "ANXIETY": "A feeling of worry or unease about something",
    "ANXIOUS": "Feeling worry, unease, or nervousness",
    "ANYBODY": "Any person at all; used in questions and negatives",
    "ANYTIME": "At whatever time; no matter when",
    "APPLIED": "Put something to practical use; relevant",
    "APPOINT": "To assign a job or role to someone officially",
    "APPROVE": "To officially agree to or accept as satisfactory",
    "ARCHIVE": "A collection of historical documents or records",
    "ARRIVAL": "The act of reaching a destination or place",
    "ARTICLE": "A piece of writing in a newspaper or magazine",
    "ASPECTS": "Particular parts or features of something",
    "ASSAULT": "A violent physical or verbal attack on someone",
    "ATTEMPT": "To make an effort to achieve or complete something",
    "AUDIBLE": "Loud enough to be heard; able to be perceived",
    "AUTOPSY": "An examination of a body to determine cause of death",
    "AVENGER": "A person who inflicts harm in return for a wrong",
    "AVIATOR": "A person who operates the controls of an aircraft",
    "AWKWARD": "Causing difficulty or embarrassment; clumsy",
    "BALANCE": "An even distribution of weight enabling stability",
    "BALCONY": "A platform enclosed by a wall projecting from a building",
    "BALLOON": "A small rubber bag inflated with air or gas",
    "BANDAGE": "A strip of material used to bind a wound",
    "BANKING": "The business conducted by a bank; financial services",
    "BARGAIN": "A thing bought for less than usual price; a deal",
    "BARRIER": "A fence or obstruction that blocks passage",
    "BASHFUL": "Reluctant to draw attention to oneself; shy",
    "BATHING": "The activity of washing oneself or swimming",
    "BATTERY": "A device that stores and supplies electrical energy",
    "BEARING": "The way one carries oneself; relevance to a topic",
    "BECAUSE": "For the reason that; since",
    "BEDROOM": "A room furnished for sleeping in",
    "BELIEVE": "To accept something as true; to have faith in",
    "BELONGS": "Is the property or rightful possession of",
    "BENEATH": "Extending or directly underneath; at a lower level",
    "BENEFIT": "An advantage or profit gained from something",
    "BESIDES": "In addition to; apart from; as well as",
    "BETWEEN": "At, into, or across the space separating two things",
    "BEWITCH": "To cast a spell on someone; to enchant or fascinate",
    "BICYCLE": "A vehicle with two wheels propelled by pedals",
    "BILLION": "The number equal to one thousand million",
    "BIZARRE": "Very strange or unusual; out of the ordinary",
    "BLANKET": "A large piece of soft material used for warmth",
    "BLEMISH": "A flaw or imperfection that spoils appearance",
    "BLESSED": "Made holy; endowed with divine favor",
    "BLISTER": "A small bubble on the skin filled with fluid",
    "BLOCKED": "Made impassable by an obstacle; obstructed",
    "BLOSSOM": "A flower or mass of flowers on a tree or bush",
    "BLUNDER": "A stupid or careless mistake",
    "BOASTED": "Talked with excessive pride about achievements",
    "BONFIRE": "A large open-air fire used for celebration",
    "BOOKLET": "A small thin book with paper covers; a pamphlet",
    "BOULDER": "A large rock, typically worn smooth by erosion",
    "BRAVELY": "In a courageous manner; with bravery",
    "BREAKER": "A heavy ocean wave that breaks on the shore",
    "BREATHE": "To take air into the lungs and then expel it",
    "BRIGADE": "A subdivision of an army; a group of people organized",
    "BRISKLY": "In an active and energetic manner; quickly",
    "BRITTLE": "Hard but liable to break or shatter easily",
    "BROADLY": "In general terms; widely; without detail",
    "BROTHER": "A man or boy in relation to other children of his parents",
    "BROUGHT": "Past tense of 'bring'; carried to a place",
    "BROWSER": "A person or program that browses; web software",
    "BUFFALO": "A large wild ox; a city in New York State",
    "BUILDER": "A person who constructs or repairs buildings",
    "BURNING": "On fire; very hot; feeling strong emotion",
    "CABINET": "A cupboard with shelves or drawers; a body of advisors",
    "CALCIUM": "A chemical element essential for bones and teeth",
    "CALIBER": "The quality of someone's character or abilities",
    "CALLING": "A strong urge toward a profession; a vocation",
    "CAMPING": "The activity of spending a holiday living in a tent",
    "CANTEEN": "A restaurant in a workplace; a water container",
    "CAPABLE": "Having the ability or quality to do something",
    "CAPITAL": "The most important city of a country; wealth or money",
    "CAPTAIN": "The person in command of a ship, team, or group",
    "CAPTIVE": "A person who has been taken prisoner; confined",
    "CAPTURE": "To take into one's possession by force; to seize",
    "CAREFUL": "Making sure of avoiding danger or mistakes",
    "CARRIED": "Transported or moved something from one place to another",
    "CATALOG": "A complete list of items arranged systematically",
    "CAUTION": "Care taken to avoid danger; a warning",
    "CENTRAL": "Of or at the center; most important or essential",
    "CERAMIC": "Made from clay that is hardened by heat; pottery",
    "CERTAIN": "Known for sure; established beyond doubt",
    "CHAMBER": "A large room used for formal events; an enclosed space",
    "CHANNEL": "A passageway for water; a band of broadcasting frequencies",
    "CHAPTER": "A main division of a book or story",
    "CHARGER": "A device used to recharge a battery; a horse for battle",
}

def main():
    path = os.path.join("app", "src", "main", "assets", "words.json")
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    updated = 0
    missing = []

    for word_obj in data.get("3", []):
        w = word_obj["word"].upper()
        if w in DEFINITIONS_3:
            word_obj["definition"] = DEFINITIONS_3[w]
            updated += 1
        elif not word_obj.get("definition"):
            missing.append(f"3:{w}")

    for word_obj in data.get("7", []):
        w = word_obj["word"].upper()
        if w in DEFINITIONS_7:
            word_obj["definition"] = DEFINITIONS_7[w]
            updated += 1
        elif not word_obj.get("definition"):
            missing.append(f"7:{w}")

    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    print(f"Updated {updated} definitions")
    if missing:
        print(f"Still missing: {len(missing)} words: {', '.join(missing)}")
    else:
        print("All words now have definitions!")

if __name__ == "__main__":
    main()
