import json, sys

d = json.load(open('app/src/main/assets/valid_words.json', encoding='utf-8'))
sets = {k: set(v) for k, v in d.items()}
print('Counts:', {k: len(v) for k, v in sets.items()})

words3 = ['BOW','CUP','DEW','EEL','FOX','GEM','HOP','JET','KIT','MUD','RYE','SAP','TAR','VAT','WAX','YAM','ACE','AID','ANT','APE','ASH','AXE','BAY','BEE','BOG','BOX','BUD','BUS','COD','COW','CUB','DAM','DOE','ELK','EMU','FIN','FIR','FUN','GAP','GAS','GUN','HAM','IVY','OAR','ORB','ORE','PAW','PEW','POD','POT','PUB','PUP','RAW','RIM','ROW','RUG','SAW','SEA','SKI','SOD','SON','SOW','SPA','SUM','TAB','TAP','TAX','TIN','TOE','TON','TOP','TOW','TOY','TUG','WEB','WIG','WIN','WIT','WOK']
words4 = ['ARCH','ATOM','BALE','BARN','BEAK','BEAN','BEAR','BEAT','BILL','BIRD','BLOW','BOLT','BOND','BONE','BOOK','BOOT','BOWL','CAGE','CAKE','CAMP','CAPE','CARD','CAVE','CLAY','CLIP','CLUB','COAT','COLD','CONE','CORD','CORN','CROP','CROW','CURE','CURL','DAWN','DEAL','DECK','DEER','DICE','DISH','DOME','DOOR','DOWN','DRAG','DRAW','DROP','DRUM','DUCK','DUNE','DUSK','DUST','EDGE','EPIC','FACE','FARM','FERN','FILM','FISH','FLAG','FLAT','FLOW','FOAM','FOLD','FOOD','FORD','FORM','FORT','FOUR','FROG','FUEL','FULL','GAME','GATE','GEAR','GLOW','GLUE','GOAL','GOLD']
words5 = ['ABOVE','ACORN','ADULT','ALARM','ALBUM','ANGEL','APPLE','ARROW','ATLAS','ATTIC','AWAKE','AWARE','BEACH','BIRTH','BLAST','BLEND','BLISS','BLOCK','BLOOD','BLOOM','BRACE','BRAIN','BRAND','BREAK','BRINE','BRISK','BROOK','BROTH','BROWN','BUDDY','BULGE','CANAL','CARGO','CARRY','CEDAR','CHAIN','CHALK','CHARM','CHASE','CHESS','CHEST','CHIEF','CHILD','CHILL','CHIVE','CHORD','CLAIM','CLAMP','CLANG','CLEAN','CLEAR','CLERK','CLICK','CLIMB','CLING','CLOAK','CLONE','CLOTH','CLOWN','COACH','CORAL','CRAFT','CRASH','CRAWL','CREAK','CREEK','CREEP','CRIME','CRISP','CRUST','CURVE','CYCLE','DAISY','DECAY','DEPOT','DIZZY','AUDIO','AVOID','BOARD']
words6 = ['ABRUPT','ABSENT','ACTIVE','AFFORD','ARCTIC','AUTUMN','BATTLE','BEACON','BEETLE','BELONG','BISHOP','BITTER','BOTTLE','BOUNCE','BRANCH','BREATH','BRONZE','BUBBLE','BUCKET','BUDGET','BURROW','BUTTON','CANDLE','CANYON','CARBON','CARPET','CARROT','CATTLE','CAVERN','CEMENT','CHERRY','CIRCLE','CIRCUS','CITRUS','COFFEE','COLONY','COMBAT','COTTON','CRATER','CRAYON','CREDIT','CRISIS','CUSTOM','DAGGER','DAMAGE','DANGER','DEBATE','DECADE','DEFINE','DEGREE','DEPLOY','DEPUTY','DESIGN','DETAIL','DEVOUR','DIFFER','DIRECT','DIVIDE','DONKEY','DRIVEN','EFFECT','EITHER','ENABLE','ENCODE','ENDURE','ENERGY','ENGAGE','ENGINE','ENTIRE','ESCAPE','EVOLVE','EXCITE','EXHALE','EXPAND','EXPERT','FABRIC','FALCON','FAMINE','FAMOUS']
words7 = ['ABANDON','ACCOUNT','ACHIEVE','ANCIENT','ANOTHER','ATTEMPT','BATTERY','BENEATH','BREATHE','CABINET','CAPABLE','CARTOON','CEILING','CENTURY','CERTAIN','CHANNEL','CHARITY','CHICKEN','CHIMNEY','CITIZEN','CLASSIC','COLLECT','COMMAND','COMPACT','CONCERT','CONDUCT','CONNECT','CONTROL','CONVERT','CORRECT','COTTAGE','COUNTRY','CULTURE','CURIOUS','CURRENT','CURTAIN','DECLARE','DELIVER','DESERVE','DESTINY','DEVELOP','DISTANT','DIVERSE','DYNASTY','ECLIPSE','EDUCATE','ELEGANT','EMPEROR','ENCHANT','ENDLESS','ENFORCE','ENHANCE','EVENING','EXAMINE','EXAMPLE','EXPLAIN','EXPLORE','EXTREME','FASHION','FEATURE','FERTILE','FICTION','FINALLY','FISHING','FLATTEN','FLAVOUR','FOREVER','FORTUNE','FORWARD','FRAGILE','FRIENDS','FURNACE','GALLEON','GATEWAY','GLACIER','GORILLA','GRADUAL','GRANITE','HABITAT']

missing = []
for w in words3:
    if w not in sets['3']: missing.append(f'3-letter:{w}')
for w in words4:
    if w not in sets['4']: missing.append(f'4-letter:{w}')
for w in words5:
    if w not in sets['5']: missing.append(f'5-letter:{w}')
for w in words6:
    if w not in sets['6']: missing.append(f'6-letter:{w}')
for w in words7:
    if w not in sets['7']: missing.append(f'7-letter:{w}')

if missing:
    print('MISSING from valid_words.json:')
    for m in missing: print(' ', m)
else:
    print('ALL WORDS FOUND in valid_words.json!')
